apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: safe
spec:
  version: "v0.0.1"
  platforms:
  # specify installation script for linux and darwin (macOS)
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    # url for downloading the package archive:
    uri: https://github.com/example/foo/releases/v0.0.1.zip
    # sha256sum of the above archive file:
    sha256: "208fde0b9f42ef71f79864b1ce594a70832c47dc5426e10ca73bf02e54d499d0"
    # copy the used files out of the zip archive, defaults to `[{from: "*", to: "."}]`
    files:
    - from: "foo-*/unix/*.sh" # path to the files extracted from archive
      to:  "."                 # '.' refers to the root of plugin install directory
    - from: "foo-*/LICENSE"   # always install your LICENSE file
      to: "."
    bin: "kubectl-safe"  # path to the plugin executable after copying files above
  shortDescription: >-
    Safe write operations in Kubernetes
  homepage: https://github.com/esin/kubectlsafe
  description: |
    Before every write (apply, create, etc...) operation kubectl will ask you about you choise